# https://aka.ms/yaml
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs
    - "*.md"
    - appveyor.yml
    - .travis.yml

pool:
  vmImage: 'vs2017-win2016'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_UI_LANGUAGE: en
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
# https://github.com/dotnet/cli/issues/9917
# wow, we can't install global tool in azure pipelines :(
- script: |
    dotnet tool install --tool-path . Cake.Tool
    dotnet tool install --tool-path . coverlet.console
  displayName: 'Install tools'

- script: .\dotnet-cake build/build.cake --target=Rebuild
  displayName: 'Run rebuild'

- script: .\dotnet-cake build/build.cake --target=Coverage
  displayName: 'Run tests'
